package:
  name: seqtk
  version: 1.2
about:
  home: https://github.com/lh3/seqtk
  license: MIT
  summary: seqtk
build:
  number: 0
  skip: True # [osx]
source:
  fn: v1.2.tar.gz
  url: https://github.com/lh3/seqtk/archive/v1.2.tar.gz
  md5: 255ffe05bf2f073dc57abcff97f11a37
requirements:
  build:
    - gcc
    - zlib
  run:
    - gcc
    - zlib
test:
  commands:
    - seqtk sample
