package:
  name: seqtk_cf
  version: "1.2"
about:
  home: http://github.com/lh3/seqtk
  license: MIT
  summary: The famous seqtk software
build:
  number: 0
source:
  fn: v1.2.tar.gz
  url: https://github.com/lh3/seqtk/archive/v1.2.tar.gz
  md5: 255ffe05bf2f073dc57abcff97f11a37
requirements:
  build:
    - gcc # [not osx]
    - llvm # [osx]
    - zlib {{ CONDA_ZLIB}}*
  run:
    - libgcc
    - zlib {{ CONDA_ZLIB}}*
test:
  commands:
    - seqtk sample
